name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          set -e
    git pull https://Rocky11:$HF_TOKEN@huggingface.co/spaces/Rocky11/Chat_With_SQLDB main --rebase -s recursive -X theirs || { echo "Merge conflict - aborting rebase"; git rebase --abort; exit 1; }
    git push https://Rocky11:$HF_TOKEN@huggingface.co/spaces/Rocky11/Chat_With_SQLDB main
Summary
The workflow fails due to merge conflicts during git pull --rebase.
Use a merge strategy (-X theirs or -X ours) to auto-resolve simple conflicts.
Abort the rebase on conflict to prevent the workflow from hanging.
Update your workflow’s Push to hub step as shown above to fix the issue.

You can view and edit your workflow file here: .github/workflows/main.yml (ref: main)

Vekri/Chat-with-SQL-DB
How can I help you?
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
Chat-with-SQL-DB/.github/workflows
/main.yml
Go to file
t
Vekri
Vekri
Update main.yml
b514932
 · 
5 minutes ago

Code

Blame
22 lines (20 loc) · 593 Bytes
name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          set -e
          git pull https://Rocky11:$HF_TOKEN@huggingface.co/spaces/Rocky11/Chat_With_SQLDB main --rebase -s recursive -X theirs || { echo "Merge conflict - aborting rebase"; git rebase --abort; exit 1; }
          git push https://Rocky11:$HF_TOKEN@huggingface.co/spaces/Rocky11/Chat_With_SQLDB main
